### ISSUE TITLE
Domain name ideas

### ISSUE THREAD

**Issue by cchan** [sexxis/website#1]
Here's a couple of available domains! Which do you think is good? (or post your own)

wat2021.se
watse.ca

**Comment by RootLuo** [comment]
wat2021.se

I like this one

**Comment by lpan** [comment]
@cchan they are cool but not "se'xxi" enough ;)

**Comment by lpan** [comment]
Hey guys I am closing this issue for now since majority of the people prefer sexxi.xyz. However, if you guys have a better domain name idea, feel free to reopen this issue and create a poll on our facebook group :)

**Comment by cchan** [comment]
I didn't get it until now lololol

**Comment by lpan** [comment]
@cchan haha bro no worries
