### ISSUE TITLE
Static HTML is too "wet" :P

### ISSUE THREAD

**Issue by lpan** [sexxis/website#3]
Static HTML is not reusable :stuck_out_tongue: To make our markup DRYer, we need to use a JavaScript framework, a template engine or a static site generator.

Here are some options:
- Jekyll
- Handlebar
- Jade
- [Vue](https://vuejs.org/)
- React

Anything to add? @cchan

**Comment by cchan** [comment]
Angular!!

There's also Backbone and Ember.

**Comment by davepagurek** [comment]
Use the only one true framework https://github.com/jneen/balls

**Comment by lpan** [comment]
ayyyyy

**Comment by lpan** [comment]
A JS framework is way too overkill :stuck_out_tongue:
