### ISSUE TITLE
Sass-lint does not fail on warnings

### ISSUE THREAD

**Issue by cchan** [sexxis/website#8]
The only thing missing with PR #7 is that sass-lint is giving weird warnings about indentation that I don't understand. I've submitted sasstools/sass-lint#736 to see what's up.

So once this is fixed, on our end we need to add failure on warning, not only on error, for sass-lint. Should be pretty easy streaming to a function similar to [sassLint.failOnError](https://github.com/sasstools/sass-lint/blob/ff4f5f1a74d73490bca6ccae055db5d24f4b3512/index.js#L292).

**Comment by lpan** [comment]
Dude, the only difference between an `error` and a `warning` is that the linter fails on an `ERROR` but it does not fail on an `WARNING` :stuck_out_tongue:

**Comment by cchan** [comment]
Hmm, there might be some setting that causes all the checks currently outputted as warnings in sass-lint to be converted to errors.
(just be as strict as possible with the linting!)
